### ISSUE TITLE
Sunset `celo-org/payments` repo or transition ownership to Valora

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/payments#37]
Definition of done: 
- [x] Consider transfering ownership to Valora (give write permission to make updates) if interested, 
- [x] Sunset repo (including message in README) - archive repo

**Comment by arthurgousset** [comment]
Sprint planning Wed, Mar 15: 

- Valora do want it
- [x] Decide to speak with Valora about ownership (more officially "we don't support this publicly, you can use it though"

**Comment by arthurgousset** [comment]
(for future reference)
[Valora doesn't want ownership over the repo and will deprecate the feature in Valora soon](https://celo-org.slack.com/archives/CL7BVQPHB/p1695803427324009?thread_ts=1695640964.529459&cid=CL7BVQPHB)

**Comment by arthurgousset** [comment]
Archiving this repo going forward
